In [4]:
#load libraries
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
#set working directory to folder of files

setwd("/home/user/Caitlin-Sandbox/climate-attitude-capstone-project/data/disaster-event-data/state-event-data")

In [6]:
# Get a list of all files ending with ".csv" in the current directory
files_list <- list.files(pattern = "*.csv",full.names = TRUE)

print(files_list)

 [1] "./events-AK-2008-2024.csv" "./events-AL-2008-2024.csv"
 [3] "./events-AR-2008-2024.csv" "./events-AZ-2008-2024.csv"
 [5] "./events-CA-2008-2024.csv" "./events-CO-2008-2024.csv"
 [7] "./events-CT-2008-2024.csv" "./events-DE-2008-2024.csv"
 [9] "./events-FL-2008-2024.csv" "./events-GA-2008-2024.csv"
[11] "./events-HI-2008-2024.csv" "./events-IA-2008-2024.csv"
[13] "./events-ID-2008-2024.csv" "./events-IL-2008-2024.csv"
[15] "./events-IN-2008-2024.csv" "./events-KS-2008-2024.csv"
[17] "./events-KY-2008-2024.csv" "./events-LA-2008-2024.csv"
[19] "./events-MA-2008-2024.csv" "./events-MD-2008-2024.csv"
[21] "./events-ME-2008-2024.csv" "./events-MI-2008-2024.csv"
[23] "./events-MN-2008-2024.csv" "./events-MO-2008-2024.csv"
[25] "./events-MS-2008-2024.csv" "./events-MT-2008-2024.csv"
[27] "./events-NC-2008-2024.csv" "./events-ND-2008-2024.csv"
[29] "./events-NE-2008-2024.csv" "./events-NH-2008-2024.csv"
[31] "./events-NJ-2008-2024.csv" "./events-NM-2008-2024.csv"
[33] "./events-NV-2008-2024.csv" "./events-NY-2008-2024.csv"
[35] "./events-OH-2008-2024.csv" "./events-OK-2008-2024.csv"
[37] "./events-OR-2008-2024.csv" "./events-PA-2008-2024.csv"
[39] "./events-RI-2008-2024.csv" "./events-SC-2008-2024.csv"
[41] "./events-SD-2008-2024.csv" "./events-TN-2008-2024.csv"
[43] "./events-TX-2008-2024.csv" "./events-UT-2008-2024.csv"
[45] "./events-VA-2008-2024.csv" "./events-VT-2008-2024.csv"
[47] "./events-WA-2008-2024.csv" "./events-WI-2008-2024.csv"
[49] "./events-WV-2008-2024.csv" "./events-WY-2008-2024.csv"

In [8]:
# Read all files and combine them into a single data frame
all_data <- set_names(files_list) %>%
map_dfr(read_csv, skip = 2, .id = "source_file") %>%
mutate(
state = str_extract(basename(source_file), "(?<=events-)[A-Z]{2}")
)
# View the combined data
head(all_data)

Rows: 4 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 70 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 63 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 22 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 27 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 57 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 25 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 16 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 52 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 91 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 1 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 61 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 19 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 91 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 67 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 75 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 59 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 61 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 26 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 57 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 7 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 42 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 38 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 88 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 60 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 22 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 77 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 13 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 47 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 10 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 49 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 28 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 17 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 62 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 67 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 85 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 24 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 77 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 17 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 64 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 21 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 79 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 142 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 14 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 77 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 7 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 23 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 45 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 20 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 23 Columns: 7

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Name, Disaster
dbl (5): Begin Date, End Date, CPI-Adjusted Cost, Unadjusted Cost, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  source_file
1 ./events-AK-2008-2024.csv
2 ./events-AK-2008-2024.csv
3 ./events-AK-2008-2024.csv
4 ./events-AK-2008-2024.csv
5 ./events-AL-2008-2024.csv
6 ./events-AL-2008-2024.csv
  Name                                                   Disaster
1 Western Wildfires (Summer-Fall 2009)                   Wildfire
2 Western and Alaskan Wildfires (Summer-Fall 2015)       Wildfire
3 California and Alaska Wildfires (Summer-Fall 2019)     Wildfire
4 Western Wildfires (Spring-Fall 2022)                   Wildfire
5 Southeast Tornadoes and Severe Weather (February 2008) Severe Storm
6 Hurricane Gustav (September 2008)                      Tropical Cyclone
  Begin Date End Date CPI-Adjusted Cost Unadjusted Cost Deaths state
1 20090601   20091130 1477.4            1011.9          10     AK
2 20150601   20151130 3996.9            3028.0          12     AK
3 20190601   20191130 5535.0            4500.0           3     AK
4 20220401   20221130 3327.9            3110.0          17     AK
5 20080205   20080206 1805.3            1211.6          57     AL
6 20080831   20080903 8635.7            5997.0          53     AL

In [12]:
#filter for just the hurricane data and the columns being used

hurricane_data <- all_data %>%
    filter(Disaster =="Tropical Cyclone") %>%
    select(state, Name, "Begin Date", "CPI-Adjusted Cost", Deaths) %>%
filter(`CPI-Adjusted Cost` > 50000)


hurricane_data

   state Name                              Begin Date CPI-Adjusted Cost Deaths
1  AL    Hurricane Harvey (August 2017)    20170825   160000.0           89
2  AL    Hurricane Irma (September 2017)   20170906    64000.0           97
3  AL    Hurricane Ida (August 2021)       20210829    84608.1           96
4  AL    Hurricane Helene (September 2024) 20240924    78721.0          219
5  AR    Hurricane Ida (August 2021)       20210829    84608.1           96
6  CT    Hurricane Sandy (October 2012)    20121030    88453.9          159
7  CT    Hurricane Ida (August 2021)       20210829    84608.1           96
8  DE    Hurricane Sandy (October 2012)    20121030    88453.9          159
9  DE    Hurricane Ida (August 2021)       20210829    84608.1           96
10 FL    Hurricane Irma (September 2017)   20170906    64000.0           97
11 FL    Hurricane Ida (August 2021)       20210829    84608.1           96
12 FL    Hurricane Ian (September 2022)    20220928   119626.0          152
13 FL    Hurricane Helene (September 2024) 20240924    78721.0          219
14 GA    Hurricane Irma (September 2017)   20170906    64000.0           97
15 GA    Hurricane Ida (August 2021)       20210829    84608.1           96
16 GA    Hurricane Ian (September 2022)    20220928   119626.0          152
17 GA    Hurricane Helene (September 2024) 20240924    78721.0          219
18 IN    Hurricane Helene (September 2024) 20240924    78721.0          219
19 KY    Hurricane Ida (August 2021)       20210829    84608.1           96
20 KY    Hurricane Helene (September 2024) 20240924    78721.0          219
21 LA    Hurricane Harvey (August 2017)    20170825   160000.0           89
22 LA    Hurricane Ida (August 2021)       20210829    84608.1           96
23 MA    Hurricane Sandy (October 2012)    20121030    88453.9          159
24 MA    Hurricane Ida (August 2021)       20210829    84608.1           96
25 MD    Hurricane Sandy (October 2012)    20121030    88453.9          159
26 MD    Hurricane Ida (August 2021)       20210829    84608.1           96
27 MS    Hurricane Harvey (August 2017)    20170825   160000.0           89
28 MS    Hurricane Ida (August 2021)       20210829    84608.1           96
29 NC    Hurricane Sandy (October 2012)    20121030    88453.9          159
30 NC    Hurricane Harvey (August 2017)    20170825   160000.0           89
31 NC    Hurricane Irma (September 2017)   20170906    64000.0           97
32 NC    Hurricane Ida (August 2021)       20210829    84608.1           96
33 NC    Hurricane Ian (September 2022)    20220928   119626.0          152
34 NC    Hurricane Helene (September 2024) 20240924    78721.0          219
35 NH    Hurricane Sandy (October 2012)    20121030    88453.9          159
36 NJ    Hurricane Sandy (October 2012)    20121030    88453.9          159
37 NJ    Hurricane Ida (August 2021)       20210829    84608.1           96
38 NY    Hurricane Sandy (October 2012)    20121030    88453.9          159
39 NY    Hurricane Ida (August 2021)       20210829    84608.1           96
40 OH    Hurricane Sandy (October 2012)    20121030    88453.9          159
41 OH    Hurricane Helene (September 2024) 20240924    78721.0          219
42 PA    Hurricane Sandy (October 2012)    20121030    88453.9          159
43 PA    Hurricane Ida (August 2021)       20210829    84608.1           96
44 RI    Hurricane Sandy (October 2012)    20121030    88453.9          159
45 RI    Hurricane Ida (August 2021)       20210829    84608.1           96
46 SC    Hurricane Irma (September 2017)   20170906    64000.0           97
47 SC    Hurricane Ian (September 2022)    20220928   119626.0          152
48 SC    Hurricane Helene (September 2024) 20240924    78721.0          219
49 TN    Hurricane Harvey (August 2017)    20170825   160000.0           89
50 TN    Hurricane Ida (August 2021)       20210829    84608.1           96
51 TN    Hurricane Helene (September 2024) 20240924    78721.0          219
52 TX    Hurricane Harvey (August 2017)    20170825   160000.0           89
53 VA    Hurricane Sandy (October 2012)    20121030    88453.9          159
54 VA    Hurricane Ida (August 2021)       20210829    84608.1           96
55 VA    Hurricane Ian (September 2022)    20220928   119626.0          152
56 VA    Hurricane Helene (September 2024) 20240924    78721.0          219
57 WV    Hurricane Sandy (October 2012)    20121030    88453.9          159
58 WV    Hurricane Ida (August 2021)       20210829    84608.1           96
59 WV    Hurricane Helene (September 2024) 20240924    78721.0          219

In [0]:

#clean the spaces from the column names
#Remove disaster type column
#remove spaces from disaster column
#separate month and year from name column to own column (or remove and use start date only)
#filter for disasters over $50B
#code source file to state then state to region
#remove duplicate disaster names with same region
#fix date column
#join data frames by regions 
#analyze by